### ISSUE TITLE
Windows 10 Installation Error

### ISSUE THREAD

**Issue by thatguychrisw** [spark/particle-dev-app#15]
It appears that the installer is trying to create a directory that happens to be invalid.

`2017-03-22 19:14:32> Program: Starting Squirrel Updater: --install .
2017-03-22 19:14:32> Program: Starting install, writing to C:\Users\Christopher Willard\AppData\Local\SquirrelTemp
2017-03-22 19:14:32> Program: About to install to: C:\Users\Christopher Willard\AppData\Local\particledev
2017-03-22 19:14:32> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Christopher Willard\AppData\Local\particledev\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2017-03-22 19:14:32> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Christopher Willard\AppData\Local\SquirrelTemp
2017-03-22 19:14:32> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-03-22 19:14:32> ApplyReleasesImpl: Writing files to app directory: C:\Users\Christopher Willard\AppData\Local\particledev\app-1.8.0
2017-03-22 19:14:57> IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<<installPackageToAppDir>b__ad>d__bd.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
2017-03-22 19:14:57> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<<installPackageToAppDir>b__ad>d__bd.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
`

**Comment by suda** [comment]
@thatguychrisw sorry to hear that. We'll look into this. In the meantime, you can try the [zipped version](https://github.com/spark/particle-dev-app/releases/tag/v1.8.0) of Particle Dev App

**Comment by thatguychrisw** [comment]
I get the same error when I try to extract it, but after skipping the folders with invalid names it does work.

**Comment by thatguychrisw** [comment]
Here is a screenshot of the extraction process.

<img width="338" alt="too-long-dir" src="https://cloud.githubusercontent.com/assets/480344/24246164/742db550-0f9c-11e7-8854-9943b9db5ed6.PNG">
