### ISSUE TITLE
Uncaught TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by Raelx** [spark/particle-dev-app#19]
[Enter steps to reproduce below:]

1. Start Particle Dev, it brings up last project by default, one .ino file open
2. Select device (photon)
3. Wait a few minutes
4. Does not seem to affect function, still complies and flashes. you just lose the left side of the window to error messages.

**Atom Version**: 1.8.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [particle-dev](https://github.com/spark/particle-dev) package, v0.1.20

### Stack Trace

Uncaught TypeError: Cannot read property 'error' of undefined

```
At C:\Users\mikesej\AppData\Local\particledev\app-1.8.0\resources\app.asar\node_modules\particle-dev\node_modules\spark\lib\spark.js:116

TypeError: Cannot read property 'error' of undefined
    at [object Object].Spark.normalizeErr (C:\Users\mikesej\AppData\Local\particledev\app-1.8.0\resources\app.asar\node_modules\particle-dev\node_modules\spark\lib\spark.js:116:19)
    at [object Object].<anonymous> (C:\Users\mikesej\AppData\Local\particledev\app-1.8.0\resources\app.asar\node_modules\particle-dev\node_modules\spark\lib\spark.js:151:16)
    at Request.self.callback (C:\Users\mikesej\AppData\Local\particledev\app-1.8.0\resources\app.asar\node_modules\nodegit\node_modules\request\request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\mikesej\AppData\Local\particledev\app-1.8.0\resources\app.asar\node_modules\nodegit\node_modules\request\request.js:1041:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\mikesej\AppData\Local\particledev\app-1.8.0\resources\app.asar\node_modules\nodegit\node_modules\request\request.js:968:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

### Commands

```
  2x -0:44.5.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:44.2.0 particle-dev:update-login-status (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:44.1.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
  2x -0:44 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:43.7.0 particle-dev:update-login-status (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:43.6.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:43.5.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:40.5.0 particle-dev:select-device (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:33.5.0 particle-dev:update-core-status (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:33.4.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:33.4.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:31.1.0 particle-dev:compile-cloud (atom-text-editor.editor)
     -0:31 window:save-all (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
  2x -0:31 particle-dev:update-compile-status (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:29.5.0 particle-dev:core-status-updated (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:19.4.0 particle-dev:flash-cloud (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "projectHome": "C:\\Users\\mikesej\\Google Drive\\Particle\\projects",
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by suda** [comment]
Hi! Could you remove the `.particle` folder from `C:\Users\mikesej`, restart Particle Dev and see if this helps?
