### ISSUE TITLE
Linux: '(...).runParticleCommand is not a function'

### ISSUE THREAD

**Issue by mjgorman** [spark/particle-dev-app#20]
OS:
Solus Linux (4.9.32-31.lts kernel)

What I Did: 
apm install particle-dev-complete
started atom
clicked 'Start a new project' Named it and clicked okay. 
Received error that '(...).runParticleCommand is not a function'

What I expected:
To start a new project

**Comment by suda** [comment]
Hi Michael! Could you open Atom's list of installed packages and post a screen shot?

**Comment by mjgorman** [comment]
![screenshot from 2017-07-11 07-27-17](https://user-images.githubusercontent.com/5741377/28073402-66495498-660a-11e7-97bc-5abb3e453e20.png)

Grabbed from apm list. Too large in the UI to screenshot.

**Comment by mjgorman** [comment]
@suda 

More info: Atom v1.18.0 
node: v7.10.0
npm: 4.2.0

If there is anything easy to work around this I'd appreciate it. I've been having to use chrome remote desktop to run the IDE on my windows box at home which is a terrible experience.

**Comment by suda** [comment]
Thanks Michael! Can you update all packages and see if the error persists?

We've released:
* particle-dev @ v0.1.23
* particle-dev-profiles @ v0.2.0
* particle-dev-cloud-variables @ v0.1.1
* particle-dev-cloud-functions @ v0.1.1

This combination should fix this bug.

**Comment by mjgorman** [comment]
@suda  Okay, ran the update. Now I'm getting total failure loading particle-dev-profiles package.  I've attempted an apm rebuild with no success.  

Also tried removing all the packages, clearing caches and re-installing. Same issue. 
Here is the stack trace provided. 

```
Error: Cannot find module './objects/Device'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/mgorman/.atom/packages/particle-dev-profiles/src/profile-manager.js:3:34)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/home/mgorman/.atom/packages/particle-dev-profiles/src/main.js:11:20)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:253:25)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:603:52)
    at /usr/share/atom/resources/app/src/atom-environment.js:846:34
```

**Comment by suda** [comment]
Can you run `apm rebuild-module-cache`? Also is `particle-dev-profiles` at 0.2.0?

**Comment by mjgorman** [comment]
apm rebuild-module-cache results in no change. Yes on the version: 

```
Community Packages (12) /home/mgorman/.atom/packages
├── atom-django@0.3.2
├── autocomplete-python@1.9.1
├── console-panel@0.2.1
├── django-templates@0.5.0
├── particle-dev@0.1.23
├── particle-dev-cloud-functions@0.1.1
├── particle-dev-cloud-variables@0.1.1
├── particle-dev-complete@1.0.2
├── particle-dev-libraries@0.2.19
├── particle-dev-profiles@0.2.0
├── platformio-ide-terminal@2.5.3
└── tool-bar@1.1.0
```

**Comment by suda** [comment]
Hmmm, this is really bizarre. Maybe removing `~/.atom/compile-cache` would help? The module should definitely be there (you can test it with `stat ~/.atom/packages/particle-dev-profiles/src/objects/Device.js`)

**Comment by mjgorman** [comment]
```
mgorman@gormblade ~ $ ls -lash /home/mgorman/.atom/packages/particle-dev-profiles/src/objects/
total 12K
4.0K drwxrwxr-x 2 mgorman mgorman 4.0K Jul 12 08:56 .
4.0K drwxrwxr-x 3 mgorman mgorman 4.0K Jul 12 08:56 ..
4.0K -rw-rw-r-- 1 mgorman mgorman 1.8K Jul 12 08:56 device.js
```

Looks like a capitalization issue?

**Comment by suda** [comment]
Doh! The drawback of running on a case-insensitive fs... I just released 0.2.1 which should fix this.

**Comment by mjgorman** [comment]
Ah yeah, We've had so many issues with that at work developing on mac and then pushing up to amazon Linux boxes.

**Comment by mjgorman** [comment]
Seems to be working now, however some of the features seem to be missing. New project and the library search stuff is gone. Is that expected behavior?

**Comment by suda** [comment]
`particle-dev-libraries` has been updated to v0.2.20 with a fix. Are the buttons back after the update?

**Comment by mjgorman** [comment]
@suda Very close now. I can create projects and I can search for Libraries, but clicking the "Use" button doesn't seem to do anything.

**Comment by suda** [comment]
If you look into `project.properties` file, was the library added? There's a known bug where [when adding a library to a project the notification is no longer being shown](https://github.com/spark/particle-dev-libraries/issues/30).

**Comment by mjgorman** [comment]
Negative. I cleaned out and checked my project.properties file and no dependencies line was added.

**Comment by mjgorman** [comment]
If that's another bug, i guess its not related to this original post. We can probably close this and move to another issue if you like.

**Comment by suda** [comment]
Yes, it's definitely related to the issue mentioned above. We can investigate it there
